project_name: helium

monorepo:
  tag_prefix: helium/

builds:
  - id: helium
    dir: ./helium/
    binary: helium
    goos:
      - linux
    goarch:
      - amd64
      - arm64

nfpms:
  - id: helium
    package_name: helium
    file_name_template: "{{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}"
    vendor: Fosshost 
    homepage: https://github.com/fosshostorg/aarch64/tree/main/daemons
    maintainer: Hampton Moore <hampton@fosshost.org>
    description: AArch64 VM Power State change consumer 
    license: MIT
    section: utils
    priority: extra
    builds:
      - helium
    formats:
      - deb