project_name: aarch64-daemons 

before:
  hooks:
    - go mod download

builds:
  - id: hydrogen
    dir: hydrogen
    binary: hydrogen
    goos:
      - linux
    goarch:
      - amd64
      - arm64
  - id: helium
    dir: helium
    binary: helium
    goos:
      - linux
    goarch:
      - amd64
      - arm64

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

nfpms:
  - id: aarch64-daemons
    package_name: aarch64-daemons 
    file_name_template: "{{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}"
    vendor: Fosshost 
    homepage: https://github.com/fosshostorg/aarch64/tree/main/daemons
    maintainer: Hampton Moore <hampton@fosshost.org>
    description: Various daemons used at fosshost to control the aarch64 servers 
    license: MIT
    section: utils
    priority: extra
    builds:
      - hydrogen
      - helium
    formats:
      - deb
      - rpm

publishers:
  - name: fury.io
    ids:
      - voucher
    dir: "{{ dir .ArtifactPath }}"
    cmd: curl -s -F package=@{{ .ArtifactName }} https://{{ .Env.FURY_TOKEN }}@push.fury.io/fosshost/