- name: Check if ssh key exists
  stat:
    path: /root/.ssh/id_ed25519
  register: ssh_keyfile

- name: Create SSH key
  shell: ssh-keygen -t ed25519 -f /root/.ssh/id_ed25519 -o -a 100 -N ""
  when: not ssh_keyfile.stat.exists

- name: Make directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - /opt/aarch64/images/
    - /opt/aarch64/vms/

- name: Get images
  get_url:
    url: "{{ oses[item] }}"
    dest: "/opt/aarch64/images/{{ item }}.qcow2"
  with_items: "{{ oses }}"
