- name: Check if ssh key exists
  stat:
    path: /root/.ssh/id_ed25519
  register: ssh_keyfile

- name: Create SSH key
  shell: ssh-keygen -t ed25519 -f /root/.ssh/id_ed25519 -o -a 100 -N ""
  when: not ssh_keyfile.stat.exists

- name: Copy libvirt-sshd unit file
  template:
    src: libvirt-sshd.service
    dest: /lib/systemd/system/libvirt-sshd.service
  register: libvirt_service_file

- name: Restart libvirt-sshd
  systemd:
    name: libvirt-sshd
    state: restarted
    daemon_reload: true
  when: libvirt_service_file.changed

- name: Start and enable libvirt-sshd
  systemd:
    name: libvirt-sshd
    state: started
    enabled: yes

- name: Make directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - /opt/aarch64/images/
    - /opt/aarch64/vms/

- name: Get images
  get_url:
    url: "{{ oses[item].url }}"
    dest: "/opt/aarch64/images/{{ item }}.qcow2"
  with_items: "{{ oses }}"
