- name: Update fosshost-hydrogen 
  apt:
    name: "fosshost-hydrogen"
    state: latest
    update_cache: yes
  register: hydrogen
 
- name: Restart fosshost-hydrogen 
  systemd:
    state: restarted
    daemon_reload: yes
    name: fosshost-hydrogen
  when: hydrogen.changed

- name: Update fosshost-beryllium 
  apt:
    name: "fosshost-beryllium"
    state: latest
    update_cache: yes
  register: beryllium
 
- name: Restart fosshost-beryllium
  systemd:
    state: restarted
    daemon_reload: yes
    name: fosshost-beryllium
  when: beryllium.changed
