hostname: {{ vms[item].hostname }}
manage_etc_hosts: true
users:
  - name: root
    ssh-authorized-keys:
    {% for ssh_key in vms[item].ssh_keys %}
  - {{ ssh_key }}
    {% endfor %}
ssh_pwauth: true
disable_root: false
chpasswd:
  list: root:shape
  expire: False
final_message: "system up after $UPTIME seconds"
