#cloud-config
hostname: {{ item.hostname }}
manage_etc_hosts: true
users:
  - name: root
ssh_pwauth: true
disable_root: false
chpasswd:
  list: root:{{ item.temp_password }}
  expire: False
final_message: "system up after $UPTIME seconds"
