#cloud-config
hostname: {{ item.hostname }}
manage_etc_hosts: true
users:
  - name: root
ssh_pwauth: true
disable_root: false
chpasswd:
  list: root:{{ item.password }}
  expire: False
final_message: "system up after $UPTIME seconds"
runcmd:
{% if item.os == "ubuntu" or item.os == "rocky" %}
  - ip link set dev enp1s0 down
  - ip link set dev enp1s0 name eth0
  - ip link set dev enp1s0 up
  - netplan apply
{% endif %}
  - sed -ri 's/^#?PermitRootLogin\s+.*/PermitRootLogin yes/' /etc/ssh/sshd_config
{% if item.os == "ubuntu" or item.os == "debian" %}
  - systemctl restart sshd
{% endif %}
{% if item.os == "ubuntu" %}
  - sed -i 's/^GRUB_CMDLINE_LINUX_DEFAULT.*/GRUB_CMDLINE_LINUX_DEFAULT="quiet splash net.ifnames=0"/' /etc/default/grub
  - /usr/sbin/update-grub
{% endif %}
