- name: Check hostname
  shell: hostname
  register: node_hostname
  changed_when: False

- name: Set persistent hostname
  shell: hostnamectl set-hostname "{{ inventory_hostname }}"
  when: node_hostname.stdout != inventory_hostname

- name: Set sysctl values
  template:
    src: sysctl.conf
    dest: /etc/sysctl.conf
  register: sysctl

- name: Reload sysctl values
  shell: sysctl -p
  when: sysctl.changed
