- name: Install gunicorn python package
  pip:
    name: gunicorn

- name: create aarch64 user
  user:
    name: aarch64
    groups: aarch64
    shell: /sbin/nologin
    append: yes
    state: present
    create_home: no

- name: Copy systemd service file to server
  copy:
    src: aarch64-spy.service
    dest: /etc/systemd/system
    owner: root
    group: root
  notify:
    - Start aarch64-spy

- name: Checkout aarch64 repo
  git:
    repo: https://github.com/fosshostorg/aarch64.git
    dest: /home/aarch64/src
