- name: Provision hosts
  hosts: all
  roles:
    - bcg
#  tasks:
#    - name: Check hostname
#      shell: hostname
#      register: node_hostname
#      changed_when: False
#
#    - name: Set persistent hostname
#      shell: hostnamectl set-hostname "{{ inventory_hostname }}"
#      when: node_hostname.stdout != inventory_hostname
#
#    - name: Add natesales apt repo
#      apt_repository:
#        repo: deb [trusted=yes] https://repo.natesales.net/apt /
#        state: present
#
#    - name: Add apt repo for bird
#      apt_repository:
#        repo: deb http://deb.debian.org/debian/ sid main
#        state: present
#
#    - name: Set default release
#      copy:
#        content: APT::Default-Release "stable";
#        dest: /etc/apt/apt.conf.d/default-release
#
#    - name: Install BIRD2 from sid
#      apt:
#        update_cache: true
#        name: bird2
#        default_release: sid
#
#    - name: Install packages
#      apt:
#        install_recommends: false
#        pkg:
#          - qemu-system
#          - libvirt-clients
#          - libvirt-daemon-system
#          - cloud-image-utils
#          - virtinst
#          - bridge-utils
#          - ebtables
#          - bcg
#
#    - name: Set sysctl values
#      template:
#        src: sysctl.conf
#        dest: /etc/sysctl.conf
#      register: sysctl
#
#    - name: Reload sysctl values
#      shell: sysctl -p
#      when: sysctl.changed
#
#    - name: Check if ssh key exists
#      stat:
#        path: /root/.ssh/id_ed25519
#      register: ssh_keyfile
#
#    - name: Create SSH key
#      shell: ssh-keygen -t ed25519 -f /root/.ssh/id_ed25519 -o -a 100 -N ""
#      when: not ssh_keyfile.stat.exists
#
#    - name: Make directories
#      file:
#        path: "{{ item }}"
#        state: directory
#      with_items:
#        - /opt/aarch64/images/
#        - /opt/aarch64/vms/
