name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Set up NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"

      - name: Build frontend
        run: cd frontend ; npm i ; npm run build
